### ISSUE TITLE
Something is wrong (problem is on screenshot)

### ISSUE THREAD

**Issue by SMOG13** [ShogunPhyched/KNURE-TimeTable#13]
![f8d3e4d6-30dc-40ef-9130-51c4167edad9](https://user-images.githubusercontent.com/46304496/50577203-c69be980-0e2b-11e9-8a69-2aaaab98c40f.png)

Have this error week or two weeks already.

**Comment by ShogunPhyched** [comment]
Admins shut down API because DDoS, I can't fix this by my self.
